pgkit package, pgkit.config.ts, passing tests (#433)
Co-authored-by: Misha Kaletsky <mmkal@users.noreply.github.com>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -12,7 +12,7 @@ jobs:
     runs-on: ubuntu-latest
     services:
       postgres:
-        image: postgres:12
+        image: postgres:13
         env:
           PGPORT: '5432'
           POSTGRES_USER: postgres
@@ -36,6 +36,18 @@ jobs:
         run: |
           echo 'select 123 as test_column \gdesc' | docker exec -i postgres_github_actions psql "postgresql://postgres:postgres@localhost:5432/postgres" -f - | grep 'test_column | integer'
       - uses: actions/checkout@v2
+      - name: Set up Python
+        uses: actions/setup-python@v2
+        with:
+          python-version: 3.x
+      - name: Install python dependencies (for testing migra)
+        run: |
+          python -m pip install --upgrade pip
+          pip install setuptools
+          pip install migra
+          pip install psycopg2-binary
+          migra --help | grep 'Generate a database migration'
+          migra EMPTY postgresql://postgres:postgres@localhost:5432/postgres --unsafe || echo 'migra exited with an error code - check output'
       - uses: actions/setup-node@v2
         with:
           node-version: ${{ matrix.node-version }}
